// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AuthService service

func NewAuthServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AuthService service

type AuthService interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*AuthResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...client.CallOption) (*ValidateTokenResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...client.CallOption) (*AuthResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*UserResponse, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*AuthResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.Register", in)
	out := new(AuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*AuthResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.Login", in)
	out := new(AuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...client.CallOption) (*ValidateTokenResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.ValidateToken", in)
	out := new(ValidateTokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...client.CallOption) (*AuthResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.RefreshToken", in)
	out := new(AuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) GetUser(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.GetUser", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceHandler interface {
	Register(context.Context, *RegisterRequest, *AuthResponse) error
	Login(context.Context, *LoginRequest, *AuthResponse) error
	ValidateToken(context.Context, *ValidateTokenRequest, *ValidateTokenResponse) error
	RefreshToken(context.Context, *RefreshTokenRequest, *AuthResponse) error
	GetUser(context.Context, *GetUserRequest, *UserResponse) error
}

func RegisterAuthServiceHandler(s server.Server, hdlr AuthServiceHandler, opts ...server.HandlerOption) error {
	type authService interface {
		Register(ctx context.Context, in *RegisterRequest, out *AuthResponse) error
		Login(ctx context.Context, in *LoginRequest, out *AuthResponse) error
		ValidateToken(ctx context.Context, in *ValidateTokenRequest, out *ValidateTokenResponse) error
		RefreshToken(ctx context.Context, in *RefreshTokenRequest, out *AuthResponse) error
		GetUser(ctx context.Context, in *GetUserRequest, out *UserResponse) error
	}
	type AuthService struct {
		authService
	}
	h := &authServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AuthService{h}, opts...))
}

type authServiceHandler struct {
	AuthServiceHandler
}

func (h *authServiceHandler) Register(ctx context.Context, in *RegisterRequest, out *AuthResponse) error {
	return h.AuthServiceHandler.Register(ctx, in, out)
}

func (h *authServiceHandler) Login(ctx context.Context, in *LoginRequest, out *AuthResponse) error {
	return h.AuthServiceHandler.Login(ctx, in, out)
}

func (h *authServiceHandler) ValidateToken(ctx context.Context, in *ValidateTokenRequest, out *ValidateTokenResponse) error {
	return h.AuthServiceHandler.ValidateToken(ctx, in, out)
}

func (h *authServiceHandler) RefreshToken(ctx context.Context, in *RefreshTokenRequest, out *AuthResponse) error {
	return h.AuthServiceHandler.RefreshToken(ctx, in, out)
}

func (h *authServiceHandler) GetUser(ctx context.Context, in *GetUserRequest, out *UserResponse) error {
	return h.AuthServiceHandler.GetUser(ctx, in, out)
}
